### add book
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "year": 1925
}

### get all books
GET http://localhost:3000/api/books

### get book by id
GET http://localhost:3000/api/books/69011e8c11f0c9fbfdd2bcb9

### update book by id
PUT http://localhost:3000/api/books/69011b359b09c90fef5d68d2
Content-Type: application/json

{
    "title": "The Great Gatsby - Updated Edition",
    "author": "F. Scott Fitzgerald",
    "year": 1926
}
### delete book by id
DELETE http://localhost:3000/api/books/69011b507a024c8a63d1ca78